service: serverless-template

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-prune-plugin
  # - serverless-create-global-dynamodb-table
  # - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: dev #dev/prd
  region: eu-west-1
  lambdaHashingVersion: 20201221
  

  #iamRoleStatements:
  #

  environment:
    #
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    # LOCALHOST: http://localhost:8000

#resources:
# Resources:
#

#functions: ${file(src/handlers/index.yml):Handlers}

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

  prune: # automatically prune old lambda versions
    automatic: true
    number: 3

  # local dynamodb server
  # dynamodb:
  #   stages:
  #     - local
  #   start:
  #     port: 8000
  #     migrate: true
  #     seed: true
