service: serverlesss-template

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-create-global-dynamodb-table
  - serverless-prune-plugin
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'local'} #dev/prd
  region: eu-west-1

  #iamRoleStatements:
  #

  environment:
    #
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    LOCALHOST: http://localhost:8000

#resources:
# Resources:
#

#functions: ${file(src/handlers/index.yml):Handlers}

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

  prune: # automatically prune old lambda versions
    automatic: true
    number: 3

  # local dynamodb server
  dynamodb:
    stages:
      - local
    start:
      port: 8000
      migrate: true
      seed: true
