service: serverless-template

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-prune-plugin
  

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: dev #dev/prd
  region: eu-west-1
  lambdaHashingVersion: 20201221

  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    # Table Names Below


functions: ${file(src/handlers/index.yml):Handlers}

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

  prune: # automatically prune old lambda versions
    automatic: true
    number: 3
